baseURL = 'https://seshadri-05.github.io/'
languageCode = 'en-us'
title = "Seshadri's adorable lil blog"
theme = "meloxy"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Photos'
    pageRef = '/photos'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

